I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/control.rpy", line 342, in script
    d "Don't start to flatten me already. It won't lessen your punishment."
Exception: Sayer 'd' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/control.rpy", line 342, in script
    d "Don't start to flatten me already. It won't lessen your punishment."
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'd' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Pride and Submission 1.3.2
Sat Jun 05 12:39:14 2021
