I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/sim.rpy", line 10, in script call
    call screen tie
  File "game/sim.rpy", line 10, in script call
    call screen tie
  File "game/dogtraining.rpy", line 68, in script
    show m_surprise at s
TypeError: 'unicode' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/sim.rpy", line 10, in script call
    call screen tie
  File "game/sim.rpy", line 10, in script call
    call screen tie
  File "game/dogtraining.rpy", line 68, in script
    show m_surprise at s
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\ast.py", line 1183, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\ast.py", line 1153, in show_imspec
    atl=atl)
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\exports.py", line 703, in show
    img = i(img)
TypeError: 'unicode' object is not callable

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Pride and Submission 1.3
Thu Apr 30 13:04:31 2020
