I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/sim.rpy", line 12, in script call
    call screen tie
  File "game/sim.rpy", line 25, in script
    if controlStage==2 and !dogtraining:
  File "game/sim.rpy", line 25, in <module>
    if controlStage==2 and !dogtraining:
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/sim.rpy", line 12, in script call
    call screen tie
  File "game/sim.rpy", line 25, in script
    if controlStage==2 and !dogtraining:
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/sim.rpy", line 25, in <module>
    if controlStage==2 and !dogtraining:
NameError: name 'false' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Pride and Submission 1.3.2
Sat Jun 19 11:48:25 2021
